# Generated by Django 6.0.2 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歌曲名')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('album', models.CharField(blank=True, max_length=100, null=True, verbose_name='专辑')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
    ]
