# Generated by Django 6.0.2 on 2026-02-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-created_at'], 'verbose_name': '音乐', 'verbose_name_plural': '音乐'},
        ),
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='music',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径'),
        ),
    ]
