# Generated by Django 6.0.2 on 2026-02-11 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_options_music_created_at_music_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
